name = "NumericalExperiments"
uuid = "ad2e6c4f-0bdc-470d-a0f9-562d73da60c5"
authors = ["Nikos Gianniotis <ngiann@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
GPCC = "4498ab02-56af-48f6-b5af-4c1c07c71523"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
